"""empty message

Revision ID: 2e12c453fc15
Revises: 
Create Date: 2025-04-10 16:49:28.488894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e12c453fc15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wood', sa.String(), nullable=True),
    sa.Column('contour', sa.String(), nullable=True),
    sa.Column('routing', sa.String(), nullable=True),
    sa.Column('chambering', sa.Boolean(), nullable=True),
    sa.Column('binding', sa.Boolean(), nullable=False),
    sa.Column('finish', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('screws', sa.Integer(), nullable=False),
    sa.Column('spacing', sa.Integer(), nullable=True),
    sa.Column('tremolo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fretboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('fret_count', sa.Integer(), nullable=False),
    sa.Column('binding', sa.Boolean(), nullable=False),
    sa.Column('scalloped', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guitar_pickup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('magnet', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('noiseless', sa.Boolean(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware_finish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('headstock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(), nullable=True),
    sa.Column('decal_style', sa.String(), nullable=True),
    sa.Column('reverse', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inlays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('spacing', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wood', sa.String(), nullable=True),
    sa.Column('finish', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=True),
    sa.Column('truss_rod', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neck_plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('bolts', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nut',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('locking', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickguard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ply_count', sa.Integer(), nullable=True),
    sa.Column('screws', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('saddles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('string_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuning_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('locking', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('year_range', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scale_length', sa.Float(), nullable=False),
    sa.Column('relic', sa.String(length=50), nullable=False),
    sa.Column('other_controls', sa.JSON(), nullable=True),
    sa.Column('pickup_configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('neck_id', sa.Integer(), nullable=False),
    sa.Column('headstock_id', sa.Integer(), nullable=False),
    sa.Column('nut_id', sa.Integer(), nullable=False),
    sa.Column('frets_id', sa.Integer(), nullable=False),
    sa.Column('inlays_id', sa.Integer(), nullable=False),
    sa.Column('bridge_id', sa.Integer(), nullable=False),
    sa.Column('saddles_id', sa.Integer(), nullable=False),
    sa.Column('tuning_machine_id', sa.Integer(), nullable=False),
    sa.Column('string_tree_id', sa.Integer(), nullable=False),
    sa.Column('neck_plate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bridge_id'], ['bridge.id'], name=op.f('fk_model_bridge_id_bridge')),
    sa.ForeignKeyConstraint(['frets_id'], ['frets.id'], name=op.f('fk_model_frets_id_frets')),
    sa.ForeignKeyConstraint(['headstock_id'], ['headstock.id'], name=op.f('fk_model_headstock_id_headstock')),
    sa.ForeignKeyConstraint(['inlays_id'], ['inlays.id'], name=op.f('fk_model_inlays_id_inlays')),
    sa.ForeignKeyConstraint(['neck_id'], ['neck.id'], name=op.f('fk_model_neck_id_neck')),
    sa.ForeignKeyConstraint(['neck_plate_id'], ['neck_plate.id'], name=op.f('fk_model_neck_plate_id_neck_plate')),
    sa.ForeignKeyConstraint(['nut_id'], ['nut.id'], name=op.f('fk_model_nut_id_nut')),
    sa.ForeignKeyConstraint(['saddles_id'], ['saddles.id'], name=op.f('fk_model_saddles_id_saddles')),
    sa.ForeignKeyConstraint(['string_tree_id'], ['string_tree.id'], name=op.f('fk_model_string_tree_id_string_tree')),
    sa.ForeignKeyConstraint(['tuning_machine_id'], ['tuning_machine.id'], name=op.f('fk_model_tuning_machine_id_tuning_machine')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_body',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('body_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_model_body_body_id_body')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_body_model_id_model')),
    sa.PrimaryKeyConstraint('model_id', 'body_id')
    )
    op.create_table('model_controls',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('controls_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controls_id'], ['controls.id'], name=op.f('fk_model_controls_controls_id_controls')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_controls_model_id_model')),
    sa.PrimaryKeyConstraint('model_id', 'controls_id')
    )
    op.create_table('model_fretboard',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('fretboard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fretboard_id'], ['fretboard.id'], name=op.f('fk_model_fretboard_fretboard_id_fretboard')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_fretboard_model_id_model')),
    sa.PrimaryKeyConstraint('model_id', 'fretboard_id')
    )
    op.create_table('model_hardware_finish',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('hardware_finish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_finish_id'], ['hardware_finish.id'], name=op.f('fk_model_hardware_finish_hardware_finish_id_hardware_finish')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_hardware_finish_model_id_model')),
    sa.PrimaryKeyConstraint('model_id', 'hardware_finish_id')
    )
    op.create_table('model_pickguard',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('pickguard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_pickguard_model_id_model')),
    sa.ForeignKeyConstraint(['pickguard_id'], ['pickguard.id'], name=op.f('fk_model_pickguard_pickguard_id_pickguard')),
    sa.PrimaryKeyConstraint('model_id', 'pickguard_id')
    )
    op.create_table('model_pickups',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_pickups_model_id_model')),
    sa.ForeignKeyConstraint(['pickup_id'], ['guitar_pickup.id'], name=op.f('fk_model_pickups_pickup_id_guitar_pickup')),
    sa.PrimaryKeyConstraint('model_id', 'pickup_id')
    )
    op.create_table('model_plastic_color',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('plastic_color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_plastic_color_model_id_model')),
    sa.ForeignKeyConstraint(['plastic_color_id'], ['plastic_color.id'], name=op.f('fk_model_plastic_color_plastic_color_id_plastic_color')),
    sa.PrimaryKeyConstraint('model_id', 'plastic_color_id')
    )
    op.create_table('model_switch',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_switch_model_id_model')),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], name=op.f('fk_model_switch_switch_id_switch')),
    sa.PrimaryKeyConstraint('model_id', 'switch_id')
    )
    op.create_table('user_guitar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('serial_number_location', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scale_length', sa.Float(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('relic', sa.String(), nullable=False),
    sa.Column('other_controls', sa.String(), nullable=True),
    sa.Column('pickup_configuration', sa.String(), nullable=False),
    sa.Column('modified', sa.Boolean(), nullable=True),
    sa.Column('modifications', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('body_id', sa.Integer(), nullable=True),
    sa.Column('neck_id', sa.Integer(), nullable=True),
    sa.Column('headstock_id', sa.Integer(), nullable=True),
    sa.Column('fretboard_id', sa.Integer(), nullable=True),
    sa.Column('nut_id', sa.Integer(), nullable=True),
    sa.Column('frets_id', sa.Integer(), nullable=True),
    sa.Column('inlays_id', sa.Integer(), nullable=True),
    sa.Column('bridge_id', sa.Integer(), nullable=True),
    sa.Column('saddles_id', sa.Integer(), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('controls_id', sa.Integer(), nullable=True),
    sa.Column('tuning_machine_id', sa.Integer(), nullable=True),
    sa.Column('string_tree_id', sa.Integer(), nullable=True),
    sa.Column('neck_plate_id', sa.Integer(), nullable=True),
    sa.Column('pickguard_id', sa.Integer(), nullable=True),
    sa.Column('hardware_finish_id', sa.Integer(), nullable=True),
    sa.Column('plastic_color_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_user_guitar_body_id_body')),
    sa.ForeignKeyConstraint(['bridge_id'], ['bridge.id'], name=op.f('fk_user_guitar_bridge_id_bridge')),
    sa.ForeignKeyConstraint(['controls_id'], ['controls.id'], name=op.f('fk_user_guitar_controls_id_controls')),
    sa.ForeignKeyConstraint(['fretboard_id'], ['fretboard.id'], name=op.f('fk_user_guitar_fretboard_id_fretboard')),
    sa.ForeignKeyConstraint(['frets_id'], ['frets.id'], name=op.f('fk_user_guitar_frets_id_frets')),
    sa.ForeignKeyConstraint(['hardware_finish_id'], ['hardware_finish.id'], name=op.f('fk_user_guitar_hardware_finish_id_hardware_finish')),
    sa.ForeignKeyConstraint(['headstock_id'], ['headstock.id'], name=op.f('fk_user_guitar_headstock_id_headstock')),
    sa.ForeignKeyConstraint(['inlays_id'], ['inlays.id'], name=op.f('fk_user_guitar_inlays_id_inlays')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_user_guitar_model_id_model')),
    sa.ForeignKeyConstraint(['neck_id'], ['neck.id'], name=op.f('fk_user_guitar_neck_id_neck')),
    sa.ForeignKeyConstraint(['neck_plate_id'], ['neck_plate.id'], name=op.f('fk_user_guitar_neck_plate_id_neck_plate')),
    sa.ForeignKeyConstraint(['nut_id'], ['nut.id'], name=op.f('fk_user_guitar_nut_id_nut')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_user_guitar_owner_id_user')),
    sa.ForeignKeyConstraint(['pickguard_id'], ['pickguard.id'], name=op.f('fk_user_guitar_pickguard_id_pickguard')),
    sa.ForeignKeyConstraint(['plastic_color_id'], ['plastic_color.id'], name=op.f('fk_user_guitar_plastic_color_id_plastic_color')),
    sa.ForeignKeyConstraint(['saddles_id'], ['saddles.id'], name=op.f('fk_user_guitar_saddles_id_saddles')),
    sa.ForeignKeyConstraint(['string_tree_id'], ['string_tree.id'], name=op.f('fk_user_guitar_string_tree_id_string_tree')),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], name=op.f('fk_user_guitar_switch_id_switch')),
    sa.ForeignKeyConstraint(['tuning_machine_id'], ['tuning_machine.id'], name=op.f('fk_user_guitar_tuning_machine_id_tuning_machine')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_guitar_images',
    sa.Column('user_guitar_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('fk_user_guitar_images_image_id_image')),
    sa.ForeignKeyConstraint(['user_guitar_id'], ['user_guitar.id'], name=op.f('fk_user_guitar_images_user_guitar_id_user_guitar')),
    sa.PrimaryKeyConstraint('user_guitar_id', 'image_id')
    )
    op.create_table('user_guitar_pickups',
    sa.Column('user_guitar_id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['guitar_pickup.id'], name=op.f('fk_user_guitar_pickups_pickup_id_guitar_pickup')),
    sa.ForeignKeyConstraint(['user_guitar_id'], ['user_guitar.id'], name=op.f('fk_user_guitar_pickups_user_guitar_id_user_guitar')),
    sa.PrimaryKeyConstraint('user_guitar_id', 'pickup_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_guitar_pickups')
    op.drop_table('user_guitar_images')
    op.drop_table('user_guitar')
    op.drop_table('model_switch')
    op.drop_table('model_plastic_color')
    op.drop_table('model_pickups')
    op.drop_table('model_pickguard')
    op.drop_table('model_hardware_finish')
    op.drop_table('model_fretboard')
    op.drop_table('model_controls')
    op.drop_table('model_body')
    op.drop_table('model')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('tuning_machine')
    op.drop_table('switch')
    op.drop_table('string_tree')
    op.drop_table('saddles')
    op.drop_table('plastic_color')
    op.drop_table('pickguard')
    op.drop_table('nut')
    op.drop_table('neck_plate')
    op.drop_table('neck')
    op.drop_table('inlays')
    op.drop_table('image')
    op.drop_table('headstock')
    op.drop_table('hardware_finish')
    op.drop_table('guitar_pickup')
    op.drop_table('frets')
    op.drop_table('fretboard')
    op.drop_table('controls')
    op.drop_table('bridge')
    op.drop_table('body')
    # ### end Alembic commands ###
