"""empty message

Revision ID: 437f84f30251
Revises: 2e12c453fc15
Create Date: 2025-04-10 16:49:35.091067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437f84f30251'
down_revision = '2e12c453fc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    # ### end Alembic commands ###
