"""empty message

Revision ID: 48daacd3f66c
Revises: 044012d4c199
Create Date: 2025-04-11 09:39:02.722809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48daacd3f66c'
down_revision = '044012d4c199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_username', ['username'], unique=1)

    # ### end Alembic commands ###
