"""empty message

Revision ID: 998c069f6631
Revises: 48daacd3f66c
Create Date: 2025-04-11 15:49:13.073265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998c069f6631'
down_revision = '48daacd3f66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_username', ['username'], unique=1)

    # ### end Alembic commands ###
