"""adding serial number location to models

Revision ID: ad5a1972f373
Revises: b1524f1f0b6f
Create Date: 2025-05-08 10:02:13.119986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5a1972f373'
down_revision = 'b1524f1f0b6f'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add the column as nullable first
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number_location', sa.String(length=50), nullable=True))

    # Step 2: Populate existing rows with a default value
    op.execute("UPDATE model SET serial_number_location = 'N/A' WHERE serial_number_location IS NULL")

    # Step 3: Alter the column to be non-nullable
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.alter_column('serial_number_location', nullable=False)

    # Leave user index stuff as-is
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_column('serial_number_location')

    # ### end Alembic commands ###
