"""empty message

Revision ID: d8ed9de7af0d
Revises: 
Create Date: 2025-01-29 10:24:05.588167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ed9de7af0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_type', sa.String(), nullable=False),
    sa.Column('body_wood', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('finish_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bridge_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_knob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fretboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.Column('radius', sa.String(), nullable=False),
    sa.Column('frets', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('wood', sa.String(), nullable=False),
    sa.Column('finish', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neck_plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nut',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickguard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layers', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_configuration', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('string_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switch_tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('truss_rod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuning_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('years', sa.String(), nullable=True),
    sa.Column('body_id', sa.Integer(), nullable=False),
    sa.Column('neck_id', sa.Integer(), nullable=False),
    sa.Column('fretboard_id', sa.Integer(), nullable=False),
    sa.Column('nut_id', sa.Integer(), nullable=False),
    sa.Column('truss_rod_id', sa.Integer(), nullable=False),
    sa.Column('pickups_id', sa.Integer(), nullable=False),
    sa.Column('bridge_id', sa.Integer(), nullable=False),
    sa.Column('tuning_machine_id', sa.Integer(), nullable=False),
    sa.Column('string_tree_id', sa.Integer(), nullable=False),
    sa.Column('pickguard_id', sa.Integer(), nullable=False),
    sa.Column('control_knob_id', sa.Integer(), nullable=False),
    sa.Column('switch_tip_id', sa.Integer(), nullable=False),
    sa.Column('neck_plate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('fk_model_body_id_body')),
    sa.ForeignKeyConstraint(['bridge_id'], ['bridge.id'], name=op.f('fk_model_bridge_id_bridge')),
    sa.ForeignKeyConstraint(['control_knob_id'], ['control_knob.id'], name=op.f('fk_model_control_knob_id_control_knob')),
    sa.ForeignKeyConstraint(['fretboard_id'], ['fretboard.id'], name=op.f('fk_model_fretboard_id_fretboard')),
    sa.ForeignKeyConstraint(['neck_id'], ['neck.id'], name=op.f('fk_model_neck_id_neck')),
    sa.ForeignKeyConstraint(['neck_plate_id'], ['neck_plate.id'], name=op.f('fk_model_neck_plate_id_neck_plate')),
    sa.ForeignKeyConstraint(['nut_id'], ['nut.id'], name=op.f('fk_model_nut_id_nut')),
    sa.ForeignKeyConstraint(['pickguard_id'], ['pickguard.id'], name=op.f('fk_model_pickguard_id_pickguard')),
    sa.ForeignKeyConstraint(['pickups_id'], ['pickups.id'], name=op.f('fk_model_pickups_id_pickups')),
    sa.ForeignKeyConstraint(['string_tree_id'], ['string_tree.id'], name=op.f('fk_model_string_tree_id_string_tree')),
    sa.ForeignKeyConstraint(['switch_tip_id'], ['switch_tip.id'], name=op.f('fk_model_switch_tip_id_switch_tip')),
    sa.ForeignKeyConstraint(['truss_rod_id'], ['truss_rod.id'], name=op.f('fk_model_truss_rod_id_truss_rod')),
    sa.ForeignKeyConstraint(['tuning_machine_id'], ['tuning_machine.id'], name=op.f('fk_model_tuning_machine_id_tuning_machine')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guitar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_guitar_model_id_model')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_guitar_user_id_user')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('guitar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guitar_id'], ['guitar.id'], name=op.f('fk_image_guitar_id_guitar')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('guitar')
    op.drop_table('model')
    op.drop_table('user')
    op.drop_table('tuning_machine')
    op.drop_table('truss_rod')
    op.drop_table('switch_tip')
    op.drop_table('string_tree')
    op.drop_table('pickups')
    op.drop_table('pickguard')
    op.drop_table('nut')
    op.drop_table('neck_plate')
    op.drop_table('neck')
    op.drop_table('fretboard')
    op.drop_table('control_knob')
    op.drop_table('bridge')
    op.drop_table('body')
    # ### end Alembic commands ###
